services:
  # PostgreSQL Database
  ajps-database:
    image: postgres:16-alpine
    container_name: ajps-database
    environment:
      POSTGRES_DB: academic_journal_publication_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isdb62
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - ajps-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d academic_journal_publication_system"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Spring Boot Backend
  ajps-backend:
    build: 
      context: ./ajps-backend
      dockerfile: Dockerfile
    container_name: ajps-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ajps-database:5432/academic_journal_publication_system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=isdb62
      - APP_BASE_URL=http://localhost:8090
    ports:
      - "8090:8090"
    volumes:
      - backend_uploads:/app/ajps-uploads
    networks:
      - ajps-network
    depends_on:
      ajps-database:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Angular Frontend
  ajps-frontend:
    build: 
      context: ./ajps-frontend
      dockerfile: Dockerfile
    container_name: ajps-frontend
    ports:
      - "80:80"
      - "4500:80"
    networks:
      - ajps-network
    depends_on:
      ajps-backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  ajps-network:
    driver: bridge
